# Set the root logging level
quarkus.log.level=INFO

# Set the logging level for a specific package
quarkus.log.category."com.example".level=DEBUG

# Enable console logging
quarkus.log.console.enable=true

# Customize the log format
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

user.list = dummy
user.dummy.password = dummy

mechanism = simple
