# Logging settings
quarkus.log.level=INFO
quarkus.log.category."org.icatproject.authn_simple".level=DEBUG
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# List of authorised users
user.list = dummy
user.dummy.password = dummy

# Option to set the name of the authenticator, doesn't change the auth mechanism!
mechanism = simple

# Allowed IPs, example:
#ip = 130.246.0.0/16 172.16.68.0/24
