#!/usr/bin/env python
from setup_utils import *
import os

# authn.simple
def undeploy():
    app = actions.getAppName("authn_simple.ear")
    if app: actions.undeploy(app) 
    app = actions.getAppName("authn_simple")
    if app: actions.undeploy(app)
    app = actions.getAppName("authn.simple")
    if app: actions.undeploy(app) 
    
actions, arg, props = getActions("authn_simple-setup.properties", [])

prop_name = "authn_simple.properties"
prop_list = ["user.list"]

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    actions.checkNoErrors()
    
if arg == "INSTALL":   
    properties = getProperties(prop_name, prop_list)
    for v in properties["user.list"].split():
        if "user." + v + ".password" not in properties:
            abort ("user.list included " + v + " but user." + v + ".password is not defined")       
           
    actions.installFile(prop_name)
    
    try:
        undeploy()
        actions.deploy(deploymentorder=80)
        app = actions.getAppName("icat.server")
        if app: actions.restartApp(app)
    except Exception, e:
        abort(str(e))
               
if arg == "UNINSTALL":
    actions.removeFile(prop_name)
    try:
        undeploy() 
    except Exception, e:
        abort(str(e))       
