#!/usr/bin/env python
from setup_utils import *
import os

# authn.simple
def undeploy():
    app = actions.getAppName("authn_simple.ear")
    if app: actions.undeploy(app) 
    app = actions.getAppName("authn_simple")
    if app: actions.undeploy(app)
    app = actions.getAppName("authn.simple")
    if app: actions.undeploy(app) 

actions, arg, props = getActions("setup.properties", [])

prop_name = "run.properties"
prop_list = ["user.list"]

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    actions.checkNoErrors()

if arg == "INSTALL":
    properties = getProperties(prop_name, prop_list)
    for v in properties["user.list"].split():
        if "user." + v + ".password" not in properties:
            abort ("user.list included " + v + " but user." + v + ".password is not defined")       

    try:
        undeploy()
        ovfiles = [[prop_name, "WEB-INF/classes"]]
        if os.path.exists("logback.xml"): ovfiles.append(["logback.xml", "WEB-INF/classes"])
        actions.deploy(deploymentorder=80, files=ovfiles)
    except Exception as e:
        abort(str(e))

if arg == "UNINSTALL":
    try:
        undeploy() 
    except Exception as e:
        abort(str(e))
