name: CI Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - quarkus_auth_simple

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build native executable and run tests
        run: ./mvnw package -Dnative -Dquarkus.native.container-build=true

      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.native -t quarkus-app .