name: CI Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - quarkus_auth_simple

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build native executable for arm64
        run: |
          ./mvnw package -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args="--target-platform=linux-arm64"


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: src/main/docker/Dockerfile.native
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.HARBOR_URL }}/authn_simple:${{ github.ref_name }}